"""`arch/model.yaml` — the git-tracked half of the architect's instrument.

The file has two halves and one rule about each. The **authored** half is judgement: the
layer partition, the permitted-dependency rules, the seams, and the refactors that were
tried and rejected with a pointer to the graph node holding why. Nothing regenerates it.
The **derived** half is measurement: the edge list, the metric block, the scan id. It is
rewritten in full on every scan and committed, so a structural change shows up as a diff
in a review rather than as a number in a session nobody kept.

Both live in git because the design's round-1 question — can a model file be committed
when half of it is generated — was closed with "commit it": a derived section that is
not in the tree cannot be diffed, and the diff *is* the artifact. The edge list is one
line per edge for exactly that reason.

**Regeneration is textual, not a YAML round-trip.** Everything above the derived marker
is preserved byte for byte, because a parse-and-dump cycle would silently eat the
authored half's comments — and the authored half is prose that argues for a boundary,
which is the part worth keeping. The known failure mode this file has is the authored
half rotting while the derived half stays fresh and makes the whole document look
maintained; `stale_authored_paths` exists to make that visible rather than to prevent it.
"""

from __future__ import annotations

import fnmatch
import hashlib
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from thalamus.arch.extractor import DependencyGraph, ExtractorPolicy
from thalamus.arch.metrics import Metrics, measure

# `src/thalamus/arch/model.py` -> parents[3] is the checkout root, the same anchor
# every other repo-anchored module in the tree resolves from. `arch` measures the
# repository, not whatever directory the operator happens to be standing in, so this
# is what `--repo` defaults to and what `--repo` overrides.
REPO_ROOT = Path(__file__).resolve().parents[3]

# Relative on purpose: callers join it to the repo under measurement, which `--repo`
# can point at any checkout — a `diff` scans a temporary worktree of an older commit.
MODEL_PATH = Path("arch") / "model.yaml"

DERIVED_MARKER = (
    "# ─── DERIVED ─── regenerated by `thalamus arch scan`. Do not hand-edit below this\n"
    "# line: the next scan overwrites it. Committed anyway, because the diff is the point.\n"
)

_AUTHORED_HEADER = """\
# The architect's model of this repo. Authored above the marker, measured below it.
#
# The authored half is judgement and is never regenerated: what the layers ARE, which
# dependencies are permitted, where the seams sit, and which refactors were rejected and
# why. A rule here is a claim about how this repo is supposed to be shaped; `thalamus
# arch rules` checks the measured edge list against it and reports what disagrees.
#
# `layers` and `rules` start empty. An empty partition places no module, so `arch rules`
# reports every module as unplaced rather than silently passing — declaring the layers is
# the architect's work, not the scanner's.
"""


@dataclass
class Layer:
    """A declared layer: a name and the paths that belong to it."""

    name: str
    includes: tuple[str, ...] = ()

    def contains(self, path: str) -> bool:
        return any(fnmatch.fnmatch(path, pattern) for pattern in self.includes)


@dataclass
class Rule:
    """A permitted-dependency rule, in the Lattix shape: who may depend on whom.

    Stated as an allow-list per layer because the interesting assertion is the closed
    one. "`contract` may depend on nothing" is a claim that can be violated by a single
    import; "`contract` should probably not depend on much" is not a rule at all.
    """

    layer: str
    may_depend_on: tuple[str, ...] = ()


@dataclass
class Violation:
    """One measured edge that a declared rule forbids."""

    from_path: str
    to_path: str
    from_layer: str
    to_layer: str

    def describe(self) -> str:
        return (
            f"{self.from_path} -> {self.to_path} "
            f"({self.from_layer} may not depend on {self.to_layer})"
        )


@dataclass
class ArchModel:
    """The whole file: authored judgement, plus the last scan's measurements."""

    repo: str = ""
    root_commit: str = ""
    policy: ExtractorPolicy = field(default_factory=ExtractorPolicy)
    layers: list[Layer] = field(default_factory=list)
    rules: list[Rule] = field(default_factory=list)
    seams: list[dict] = field(default_factory=list)
    rejected_refactors: list[dict] = field(default_factory=list)
    derived: dict = field(default_factory=dict)

    def layer_of(self, path: str) -> str:
        """The declared layer a module sits in, or "" when the partition misses it."""
        for layer in self.layers:
            if layer.contains(path):
                return layer.name
        return ""

    def unplaced(self, graph: DependencyGraph) -> list[str]:
        """Scanned modules the declared partition does not place.

        The architect asked for this in the first version rather than the second: a
        partition that quietly stops covering the repo turns every rule check into a
        statement about a shrinking subset, and reports green while doing it.
        """
        if not self.layers:
            return list(graph.modules)
        return [module for module in graph.modules if not self.layer_of(module)]

    def violations(self, graph: DependencyGraph) -> list[Violation]:
        """Measured edges the declared rules forbid.

        A rule is only checked for layers that declare one: an undeclared layer permits
        everything, because the alternative is that adding a layer name silently
        forbids every edge that touches it.
        """
        permitted = {rule.layer: set(rule.may_depend_on) for rule in self.rules}
        found: list[Violation] = []
        for edge in graph.counted_edges():
            from_layer = self.layer_of(edge.from_path)
            to_layer = self.layer_of(edge.to_path)
            if not from_layer or not to_layer or from_layer == to_layer:
                continue
            allowed = permitted.get(from_layer)
            if allowed is None or to_layer in allowed:
                continue
            found.append(Violation(edge.from_path, edge.to_path, from_layer, to_layer))
        return found

    def stale_authored_paths(self, graph: DependencyGraph) -> list[str]:
        """Authored path patterns that no longer match anything scanned.

        The authored half rots silently while the derived half looks maintained. A layer
        whose `includes` matches nothing, or a seam pointing at a deleted file, is the
        cheapest detectable form of that rot.

        The universe is the scanned module list, the same one `unplaced` partitions —
        not the endpoints of the edge list. A module that neither imports nor is
        imported appears in no edge, so an edge-derived universe cannot see it and
        reports the declaration that correctly places it as rot. That error only ever
        runs one way: it accuses correct declarations, and an architect who trusts it
        deletes them to clear the finding. A rot detector that induces rot is worse
        than none.
        """
        measured = set(graph.modules)
        stale: list[str] = []
        for layer in self.layers:
            for pattern in layer.includes:
                if not any(fnmatch.fnmatch(path, pattern) for path in measured):
                    stale.append(f"layer `{layer.name}` pattern `{pattern}` matches no module")
        for seam in self.seams:
            at = str(seam.get("at", ""))
            if at and at not in measured:
                stale.append(f"seam `{seam.get('name', at)}` names `{at}`, which was not scanned")
        return stale


def root_commit(repo: Path) -> str:
    """The repo's first commit — machine identity that survives moves and renames."""
    return _git(repo, "rev-list", "--max-parents=0", "HEAD").split("\n")[0]


def head_commit(repo: Path) -> str:
    return _git(repo, "rev-parse", "HEAD")


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed in {repo}: {result.stderr.strip()}")
    return result.stdout.strip()


def dirty_paths(repo: Path, policy: ExtractorPolicy) -> list[str]:
    """Tracked files under the scanned roots that differ from HEAD.

    The walk reads the working tree while the scan id names `HEAD`. With a dirty tree
    those are different codebases, and the resulting Source would assert a measurement
    of a commit that never contained it — the false-precision failure the citation
    render's "this value held at the commit named" exists to prevent. Reported by
    `arch scan`, and refused by the graph write.
    """
    status = _git(repo, "status", "--porcelain", "--untracked-files=all")
    changed: list[str] = []
    for line in status.splitlines():
        path = line[3:].strip()
        if " -> " in path:  # a rename reports both sides
            path = path.split(" -> ")[-1]
        if not path.endswith(".py"):
            continue
        if any(path.startswith(f"{root}/") for root in policy.roots) and not _excluded_path(
            path, policy
        ):
            changed.append(path)
    return sorted(changed)


def _excluded_path(path: str, policy: ExtractorPolicy) -> bool:
    return any(fnmatch.fnmatch(path, pattern) for pattern in policy.exclude)


def scan_id(repo_slug: str, commit: str, policy: ExtractorPolicy) -> str:
    """`arch:scan:<repo>:<sha7>:<policy-digest7>` — names the commit AND the rules.

    Both halves are load-bearing. The same code measured under a different policy is a
    different number, so a scan id that named only the commit would let two
    incomparable readings collide on one name.
    """
    return f"arch:scan:{repo_slug}:{commit[:7]}:{policy.digest()[:7]}"


def derived_block(graph: DependencyGraph, metrics: Metrics, commit: str, scan: str) -> dict:
    """The measured half: what this scan saw, in the shape the file stores it.

    The edge list holds every edge the walk found, including the kinds and depths the
    declared policy does not count — the walk is the observation, and discarding the
    uncounted edges would mean a policy change needs a re-scan of a commit that may no
    longer be checked out.
    """
    return {
        "scan": scan,
        "commit": commit,
        "metrics": metrics.as_block(),
        "counted_edges": metrics.dependencies,
        "recorded_edges": len(graph.edges),
        "unresolved": list(graph.unresolved),
        "edges": [edge.as_row() for edge in graph.edges],
    }


def render(model: ArchModel, derived: dict) -> str:
    """The whole file as text: authored header, policy, marker, derived block."""
    authored = {
        "repo": model.repo,
        "root_commit": model.root_commit,
        "extractor": {**model.policy.block(), "digest": model.policy.digest()},
        "layers": [{"name": layer.name, "includes": list(layer.includes)} for layer in model.layers],
        "rules": [{"layer": r.layer, "may_depend_on": list(r.may_depend_on)} for r in model.rules],
        "seams": model.seams,
        "rejected_refactors": model.rejected_refactors,
    }
    head = yaml.safe_dump(authored, sort_keys=False, width=100)
    tail = yaml.safe_dump({"derived": derived}, sort_keys=False, width=100)
    return f"{_AUTHORED_HEADER}\n{head}\n{DERIVED_MARKER}{tail}"


def regenerate(existing: str, derived: dict) -> str:
    """Replace only the derived half, preserving the authored half byte for byte."""
    marker_start = existing.find(DERIVED_MARKER.splitlines()[0])
    authored = existing[:marker_start] if marker_start != -1 else existing.rstrip() + "\n\n"
    tail = yaml.safe_dump({"derived": derived}, sort_keys=False, width=100)
    return f"{authored}{DERIVED_MARKER}{tail}"


def load(path: Path) -> ArchModel:
    """Read a model file. A missing file is an empty model, not an error."""
    if not path.exists():
        return ArchModel()
    document = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return ArchModel(
        repo=str(document.get("repo", "")),
        root_commit=str(document.get("root_commit", "")),
        policy=ExtractorPolicy.from_block(document.get("extractor") or {}),
        layers=[
            Layer(name=str(entry.get("name", "")), includes=tuple(entry.get("includes") or ()))
            for entry in document.get("layers") or []
        ],
        rules=[
            Rule(layer=str(entry.get("layer", "")), may_depend_on=tuple(entry.get("may_depend_on") or ()))
            for entry in document.get("rules") or []
        ],
        seams=list(document.get("seams") or []),
        rejected_refactors=list(document.get("rejected_refactors") or []),
        derived=dict(document.get("derived") or {}),
    )


def content_hash(text: str) -> str:
    """sha256 of the model file — the scan Source's identity, as the design specified."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def build(repo: Path, graph: DependencyGraph, model: ArchModel | None = None) -> tuple[str, dict, Metrics]:
    """Produce the model file's next text for this scan. Writes nothing.

    Returns `(text, derived_block, metrics)` so a caller can hash and report before
    deciding to persist — the dry-run half of the CLI's `--write` split.
    """
    model = model or ArchModel()
    commit = head_commit(repo)
    # Resolved, because `Path(".").name` is the empty string and an empty slug would
    # silently mint `arch:scan::<sha>:<digest>` — a scan id naming no repo.
    slug = model.repo or repo.resolve().name
    model.repo = slug
    model.root_commit = model.root_commit or root_commit(repo)
    model.policy = graph.policy

    metrics = measure(graph)
    derived = derived_block(graph, metrics, commit, scan_id(slug, commit, graph.policy))

    path = repo / MODEL_PATH
    if path.exists():
        text = regenerate(path.read_text(encoding="utf-8"), derived)
    else:
        text = render(model, derived)
    return text, derived, metrics
